plugins:
  - jekyll-gist

# markdown: redcarpet

title:            'Yaroslava Lochman'
description:      'Yaroslava Lochman'
url:              https://ylochman.github.io
baseurl:          ''

author:
  name: Yaroslava
  url: https://ylochman.github.io

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
