gems: [jekyll-paginate]

# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink: /:categories/:year/:month/:day/:title

# Setup
title:            'Yaroslava Lochman'
description:      ''
url:              https://ylochman.github.io
production_url:   https://ylochman.github.io
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5
